name: List issues

on:
  workflow_dispatch: 

jobs:
  list-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: read

    steps:
    - uses: actions/checkout@v4
    - name: List issues
      env:
        GH_TOKEN: ${{ github.token }}
      run: | 
        gh issue list
